
name: Build and Unit Test

on:
  push:
    branches:
      - 'main'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: sudo apt-get install -y clang-11 libc++-11-dev libc++abi-11-dev
      
    - name: Checkout pp
      uses: actions/checkout@v2
      with:
        repository: cpp-core/pp
        path: pp
        
    - name: Checkout depends
      uses: actions/checkout@v2
      with:
        repository: cpp-core/depends
        path: depends
        
    - name: Build dependencies
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir depends/build && pushd depends/build
        cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/opt -DALL_TEST=ON ..
        make pp-depends
        popd

    - name: Build and run the tests
      run: |
        export CC=clang-11
        export CXX=clang++-11
        mkdir pp/build && pushd pp/build
        cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/opt ..
        make
        make check
        make install
        popd
        
